# Generated by Django 3.1.1 on 2020-09-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=100)),
                ('search_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
